### ISSUE TITLE
Validation in Asp.Net WebApi causes endless loop

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#144]
Basically what I wanted to do is send a ```FeatureCollection``` to my server in a ```POST``` method.
This might be a bug in WebApi but it might indicate an issue in the code here.
A similar issue can be seen here:
http://stackoverflow.com/questions/27979639/webapi-put-insufficientexecutionstackexception-with-dbgeography-type

Just create a simple webapi project, define all the converters and try and send a feature to the server, you'll see the exception:

```
at System.Runtime.CompilerServices.RuntimeHelpers.EnsureSufficientExecutionStack()
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, ValidationContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateProperties(ModelMetadata metadata, ValidationContext validationContext)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, ValidationContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateElements(IEnumerable model, ValidationContext validationContext)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, ValidationContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateProperties(ModelMetadata metadata, ValidationContext validationContext)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, ValidationContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateProperties(ModelMetadata metadata, ValidationContext validationContext)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, ValidationContext validationContext, Object container, IEnumerable`1 validators)
   at System.Web.Http.Validation.DefaultBodyModelValidator.ValidateProperties(ModelMetadata metadata, ValidationContext validationContext)
...
```

**Comment by HarelM** [comment]
P.S the following code is what I used to workaround this issue, in case anyone needs it:
```
    public class CustomBodyModelValidator : DefaultBodyModelValidator
    {
        public override bool ShouldValidateType(Type type)
        {
            return type!= typeof(Feature) && type != typeof(FeatureCollection) && base.ShouldValidateType(type);
        }
    }
```
and on ```HttpConfiguration```:
```
config.Services.Replace(typeof(IBodyModelValidator), new CustomBodyModelValidator());
```

**Comment by DGuidi** [comment]
I'm unable to verify this, and I suspect isn't related with NTS code.
You write 
> it might indicate an issue in the code

But I don't see any NTS code in the stack trace...

**Comment by HarelM** [comment]
Well, it doesn't happen if I don't use FeatureCollection and the NTS converters...
Is there a way I can help for you to be able to reproduce?

**Comment by DGuidi** [comment]
basically I need a unittest and/or a sample code that fails/crashes.

**Comment by HarelM** [comment]
I'll see what I can do.

**Comment by HarelM** [comment]
Please let me know if the following file is good enough:
It's a very simple web API project with only one controller
When running this surf to:
<localhost...>/api/values
Send a ```POST``` message with the following feature collection as body:
```{}```
This should work.
when using the following feature collection it fails:
```json
{ "type": "FeatureCollection",
    "features": [
      { "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
        "properties": {"prop0": "value0"}
        },
      { "type": "Feature",
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
            ]
          },
        "properties": {
          "prop0": "value0",
          "prop1": 0.0
          }
        },
      { "type": "Feature",
         "geometry": {
           "type": "Polygon",
           "coordinates": [
             [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
               [100.0, 1.0], [100.0, 0.0] ]
             ]
         },
         "properties": {
           "prop0": "value0",
           "prop1": {"this": "that"}
           }
         }
       ]
     }
```
[NTS-Bug.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/709476/NTS-Bug.zip)

**Comment by DGuidi** [comment]
I've take a look at the error and (my2cents) it's totally related to webapi modelbinder.

two suggestions:

1. don't use business models as viewmodels, but use dto instead.
2. this code works, and to me looks perfectly fine.
`
public async void Post()
        {
            // probably you're able to read content also without async/await...
            string json = await this.Request.Content.ReadAsStringAsync();
            GeoJsonReader reader = new GeoJsonReader();
            var collection = reader.Read<FeatureCollection>(json);
            ...
}
`

I'm closing this issue because unrelated to NTS. 
Thanks anyway for posting this.

**Comment by HarelM** [comment]
As posted above, I have a more elegant workaround, IMO 😊.
I want to use feature collection this is my view model...
When using GeoJson.Net the dto is the class as opposed to this implementation.
Unfortunately this library does not provide dto for geojson classes...
Thanks for your help and fast response!
