### ISSUE TITLE
NullReferenceException in PackedCoordinateSequence.GetCachedCoords

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#192]
Just got an exception with this at the top of the stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NetTopologySuite.Geometries.Implementation.PackedCoordinateSequence.GetCachedCoords()
   at NetTopologySuite.Geometries.Implementation.PackedCoordinateSequence.ToCoordinateArray()
   at NetTopologySuite.Algorithm.Centroid.Add(IPolygon poly)
   at NetTopologySuite.Algorithm.Centroid.Add(IGeometry geom)
   at NetTopologySuite.Geometries.Geometry.get_Centroid()
```

Looks like [this stuff](https://github.com/NetTopologySuite/NetTopologySuite/blob/65f5206a002e62b3e4ec173d6ab197e581c2fa99/NetTopologySuite/Geometries/Implementation/PackedCoordinateSequence.cs#L147-L156) should fetch `CoordRef` into a local before null-checking, since this looks like a race condition otherwise.

**Comment by airbreather** [comment]
Looks like JTS [has this problem](https://github.com/locationtech/jts/blob/e570b7621cb629639d53a47822a67120e9fa7a90/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequence.java#L104-L117) too.
