### ISSUE TITLE
Upgraded from 1.75 to 2.0.0-nuget2. Getting runtime errors.

### ISSUE THREAD

**Issue by IvanFarkas** [NetTopologySuite/NetTopologySuite#283]
I've upgraded from 1.75 to 2.0.0-nuget2 and getting runtime errors.
**Using**
.NET Core SDK 3.0.100-preview-010184
Microsoft.AspNetCore.App 3.0.0-preview-19075-0444
Microsoft.NETCore.App 3.0.0-preview-27324-5
Microsoft.EntityFrameworkCore 3.0.0-preview.19074.3

**Code**
`
CreateMap<PointDto, IGeometry>().ConvertUsing(d => NtsGeometryServices.Instance.CreateGeometryFactory(4326).CreatePoint(new Coordinate(d.X, d.Y)));
`

**Error**
`
Method 'Create' in type 'NetTopologySuite.Geometries.Implementation.CoordinateArraySequenceFactory' from assembly 'NetTopologySuite, Version=1.15.1.0, Culture=neutral, PublicKeyToken=f580a05016ebada1' does not have an implementation.
`

**StackTrace**
`
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at FR.API.Program.Main(String[] args) in C:\Projects\BSO\FirstResponse\FR.API\Program.cs:line 13
`

**Full Exception**
Autofac.Core.DependencyResolutionException
`
{"An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HostedServiceExecutor (ReflectionActivator), Services = [Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IHostedService[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.Hosting.IHostedService, Microsoft.Extensions.Hosting.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = GeoUpdateCityService (ReflectionActivator), Services = [Microsoft.Extensions.Hosting.IHostedService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IMapper (DelegateActivator), Services = [AutoMapper.IMapper], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IConfigurationProvider (DelegateActivator), Services = [AutoMapper.IConfigurationProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Exception has been thrown by the target of an invocation. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)"}	
`

**Comment by airbreather** [comment]
Arrgh, I can't quite push a package with the ideal fix to nuget.org, because NuGet/NuGetGallery#6948 is blocking me.  I'll have to find a workaround that's *almost* as good at excluding prereleases.

Regardless, the best we can do is specify that our own packages are incompatible with GeoAPI 2.x.  Once the fix finally gets pushed and you start referencing that version (or higher), the system won't stop you from doing exactly what you did unless you turn `NU1608` into an error on your own.
