### ISSUE TITLE
Can no longer add migrations after upgrading to EF Core 3?

### ISSUE THREAD

**Issue by andrejohansson** [NetTopologySuite/NetTopologySuite#349]
### Description
In dotnet core 2.2 and ef core 2.2 I added migrations using the command:
``dotnet ef migrations add AddComponentJsonConfiguration --context MyContext``

After upgrading my project to dotnet core 3 and upgrading all ef packages to 3.0.0 I can no longer add migrations.

### Steps to Reproduce
1. Upgrade project to dotnet core 3
1. Upgrade EF core to version 3.0.0
1. Install dotnet ef global tools (version 3.0.0)
1. Ugrade NetTopologySuite to version 3.0.0
1. Change all entity types from ``IPoint`` to ``Point`` due to breaking changes, eg: ``public virtual Point LocationPoint { get; set; }`` 
1. Run scaffolding command for migration: ``dotnet ef migrations add AddComponentJsonConfiguration --context MyContext``
1. Expect migration to be added but instead I get an exception: 

```
System.InvalidOperationException: The property 'Point.UserData' could not be mapped, because it is of type 'object' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'Ent
ityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidatePropertyMapping(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Sqlite.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
```

Also, why am I seeing sqlite validators in the exception? I'm using SqlServer!

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 3.0.0
- Other NetTopologySuite packages and versions: 
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: dotnet core 3.0

**Comment by airbreather** [comment]
@bricelam any ideas?

**Comment by bricelam** [comment]
@andrejohansson Can you submit a new issue on [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore/issues/new/choose) and attach a simple repro project? This is likely a bug in EF Core.

**Comment by andrejohansson** [comment]
Done!

**Comment by andrejohansson** [comment]
Problem was due to design time factory was missing ``.UseNetTopologySuite``, see https://github.com/aspnet/EntityFrameworkCore/issues/18058.
