### ISSUE TITLE
Cant resolve PolylineZM with value M

### ISSUE THREAD

**Issue by liugt34** [NetTopologySuite/NetTopologySuite#439]
Version   1.14.0.1
### Description
a PolylineZM with WKT like next:
SRID=4507;MULTILINESTRING((639766.97 3274404.094 199.324999999997 -1.79769e+308,639758.48 3274442.959 198.659 -1.79769e+308))

In PostGIS 
![image](https://user-images.githubusercontent.com/8056013/95571480-1ecd3a00-0a5b-11eb-9052-377dafbb438f.png)

NetTopologySuite.IO.ParseException
  HResult=0x80131600
  Message=Expected ')' or ',' but encountered '-1.79769e+308'
  Source=NetTopologySuite
  StackTrace:
   at NetTopologySuite.IO.WKTReader.GetNextCloserOrComma(TokenStream tokens)
   at NetTopologySuite.IO.WKTReader.GetCoordinateSequence(TokenStream tokens, Ordinates ordinateFlags, Boolean tryParen)
   at NetTopologySuite.IO.WKTReader.ReadMultiLineStringText(TokenStream tokens, GeometryFactory factory, Ordinates ordinateFlags)
   at NetTopologySuite.IO.WKTReader.ReadGeometryTaggedText(TokenStream tokens)
   at NetTopologySuite.IO.WKTReader.Read(TextReader reader)
   at NetTopologySuite.IO.WKTReader.Read(String wellKnownText)
   at ARchGL.GIS.Toolkit.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e) in D:\Projects\Documents\032_沙区管网\ARchGL.GIS.Toolkit\MainWindow.xaml.cs:line 36
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by DGuidi** [comment]
try to remove the SRID part that, from my knowledge, is parto of the [EWKT format](https://postgis.net/docs/ST_AsEWKT.html) and is not WKT compliant

**Comment by FObermaier** [comment]
Where did you get the WKT from? It is lacking `ZM` before the first opening `(`.

**Comment by DGuidi** [comment]
looks the output of the st_asewkt function in postgis, according to the screenshot posted.
