### ISSUE TITLE
Trying to use NetTopologySuite with Sqlite and EF Core, violation of Geometry constraint [geom-type or SRID not allowed]

### ISSUE THREAD

**Issue by d79ima** [NetTopologySuite/NetTopologySuite#540]
I attached a simple test app that reproduces the exception.
I just have a simple table with a single Geometry column.
After i set a value for this column and try to insert a new row into the table using EF Core DbContext.SaveChanges, get the following exception:

`SQLite Error 19: 'Table.WGS84Position violates Geometry constraint [geom-type or SRID not allowed]'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'Table.WGS84Position violates Geometry constraint [geom-type or SRID not allowed]'.
         at Microsoft.Data.Sqlite.Sql`

### System Configuration
Using the following NuGet packages:
- Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite 5.0.1
- Microsoft.EntityFrameworkCore.Sqlite 5.0.1
- Microsoft.EntityFrameworkCore 5.0.1
- OS: Windows 10 x64
- .NET Core 3.1
[TestNetTopologySuite.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/6850597/TestNetTopologySuite.zip)

**Comment by d79ima** [comment]
Only workaround i could come up with so far is to forcefully drop the triggers that are automatically generated by InitSpatialMetaData() for my table, which seems like a nasty hack. 
Do you guys see the same constraints violation? 
Any idea what is causing it?

**Comment by d79ima** [comment]
Only workaround so far i am able to find is to manually modify the generated schema migration as follows:
```
columns: table => new
                {
                    ID = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    WGS84Position = table.Column<Geometry>(type: "GEOMETRY", nullable: true)
                                       .Annotation(SqliteAnnotationNames.Srid, 4326)
                },
```

**Comment by d79ima** [comment]
Another option is to manually modify the generated schema migration to drop the spatialite trigger
`migrationBuilder.Sql("DROP TRIGGER ggi_Table_WGS84Position");`

Is there any way to force the proper SRID value into the geometry_columns metadata table without hand-modifying the generated migration code?

**Comment by d79ima** [comment]
i f ound that this fluent syntax works in DbContext.OnModelCreating without having to manually edit generated schema migrations:
```
modelBuilder.Entity<Table>()
                .Property(p => p.WGS84Position)
                .HasColumnType("point")
                .HasSrid(4326);
```

I think this is good enough.

**Comment by bricelam** [comment]
That is the correct way to configure the column's SRID. See [Spatial Data in the SQLite EF Core Provider](https://docs.microsoft.com/ef/core/providers/sqlite/spatial) for more tips.
