### ISSUE TITLE
Geometry Data Binding Bug "X called on empty Point" with Fluent Validation

### ISSUE THREAD

**Issue by GokhanAtilgan** [NetTopologySuite/NetTopologySuite#598]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'am new at NetTopologySuite and Geometry data. 
I started to develop .NetCore Web Api Application based on version 6.0.
When I'm trying to send HTTPPOST request to my Api, with Json data type and ONLY POLYGON or GEOMETRY or any GEO DATA TYPES gives me the error on Title of this issue.
On the other hand I started a fresh project without DI's or any extra NuGet's and tried to send the HTTPPOST request with the same structure. It works!
Eventually this is where i'm at;

On my main project I am using FluentValidation for my Validate System.
In my service constructor => when i remove(comment) "AddFluentValidation()" from my builder it works fine.
But when i try to put it back again (uncomment) it gives me the ERROR : 
"Specified argument was out of the range of valid values. (Parameter 'X called on empty Point')
   at NetTopologySuite.Geometries.Point.get_X()"

Just in case if anybody can't create structure, I can edit structure and issue one by one again in extended way.

### Steps to Reproduce
I opened the .net core web api with net 6.0 and installed the folowing librarys in my project:
- NetTopologySuite v2.4.0
- NetTopologySuite.IO.GeoJSON v2.0.4
- NetTopologySuite.IO.GeoJSON4STJ v2.1.1
- FluenValidation.AspNetCore 10.4.0

- After installation, I write these code in my Program.cs

```cs
builder.Services.AddControllers()
    .AddJsonOptions(o =>
    {
        o.JsonSerializerOptions.Converters.Add(new GeoJsonConverterFactory());
    })
    .AddFluentValidation();
```

- Create new model name of CreateGeoModel like that:

```cs
public string? Name { get; set; }
private Geometry _polygon;
public virtual Geometry Polygon
{
    get => _polygon;
    set
    {
        _polygon = value; //_polygon value is set correctly. But, it is get same error again.
    }
}
```

- And here is the api controller and endpoint

```cs
[Route("api/[controller]")]
[ApiController]
public class GeoTestController : ControllerBase
{
    [HttpPost]
    public IActionResult Post(CreateGeoModel zone)
    {
        //The method never fired!
        return Ok(zone);
    }
}
```
 - Here is also data that I'm sending to the my api endpoint.
 
```json
{
    "name": "Zone 1",
    "polygon": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    0.141,
                    -16.965
                ],
                [
                    4.58,
                    -10.443
                ],
                [
                    4.58,
                    -16.965
                ],
                [
                    0.141,
                    -16.965
                ]
            ]
        ]
    }
}
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.4.0
- Other NetTopologySuite packages and versions: 
             - NetTopologySuite.IO.GeoJSON v2.0.4
             - NetTopologySuite.IO.GeoJSON4STJ v2.1.1
- Environment (Operating system, version and so on): Windows 11, Visual Studio 2022 Enterprise
- .NET Framework version: 6.0
- Error Log: 

```txt
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'X called on empty Point')
   at NetTopologySuite.Geometries.Point.get_X()
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.DefaultComplexObjectValidationStrategy.Enumerator.<>c__DisplayClass13_1.<MoveNext>b__1()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container)
   at FluentValidation.AspNetCore.FluentValidationVisitor.<>n__1(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container)
   at FluentValidation.AspNetCore.FluentValidationVisitor.<>c__DisplayClass2_0.<Validate>g__BaseValidate|0() in /media/jskinner/Linux2/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 44
   at FluentValidation.AspNetCore.FluentValidationVisitor.ValidateInternal(ModelMetadata metadata, String key, Object model, Func`1 continuation) in /media/jskinner/Linux2/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 62
   at FluentValidation.AspNetCore.FluentValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container) in /media/jskinner/Linux2/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 46
   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata, Object container)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult, Object container)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:5001
User-Agent: PostmanRuntime/7.29.0
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 556
```

**Comment by FObermaier** [comment]
I have no knowledge about _FluentValidation_ but the error message you are seeing is definetely not one of NetTopologySuite.
[This page](https://docs.fluentvalidation.net/en/latest/start.html) suggest you have to create a validator yourself, maybe there is sth. wrong with yours?

**Comment by GokhanAtilgan** [comment]
Actually, I'm very confused about this problem. If I write this topic in the "FluentValidation" repository, they'll tell me the same as you do. I solved this problem. However, it is not professional way. 
The problem is showing up only in the controller parameter. 
Here is the temporary solution : 

```cs
public string? Name { get; set; }
[ValidateNever] //<--It is come from "Microsoft.AspNetCore.Mvc.ModelBinding.Validation"
public virtual Geometry Polygon {get; set;}
```

**Comment by FObermaier** [comment]
Maybe ypu don't have a validator for `Geometry` type at all as `Microsoft.AspNetCore.Mvc.ModelBinding.Validation.DefaultComplexObjectValidationStrategy` is being used.
Try to build a validator and use that.

**Comment by GokhanAtilgan** [comment]
Hi, actually I don't want to validate for Geometry. And I didn't. Fluent Validation is check automatically. In my project, I don't have any condition for validation of Geometry type. It is a bug just in the Controller binding object. I don't have much time for this. Just I wanted to help you for this bug. Thank you for your interest. My best regards.

**Comment by DGuidi** [comment]
> I don't want to validate for Geometry.

from my understanding, this is what you does after that you started using `ValidateNever` attribute, otherwise, as you said "Fluent Validation is check automatically". so you must handle the validation probavly, or with custom validation for complex objects or  avoiding entirely using the `ValidateNever` attribute

**Comment by GokhanAtilgan** [comment]
> from my understanding, this is what you does after that you started using `ValidateNever` attribute, otherwise, as you said "Fluent Validation is check automatically". so you must handle the validation probavly, or with custom validation for complex objects or avoiding entirely using the `ValidateNever` attribute

Yes, that's correct. If you try to re-create my scenario, you will understand clearly. I was never create any "Rule" for this object, but it is touch it automatically. I was used "ValidateNever" attribute top of the Geometry object, and fluent validation doesn't touch it.
