### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.7.24321.3] NetTopologySuite launch failed with error: System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed

### ISSUE THREAD

**Issue by Junjun-zhao** [NetTopologySuite/NetTopologySuite#762]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We are doing Application compatibility testing with this application against the latest .NET 9. When run this application with the latest .NET 9 build "dotnet-sdk-9.0.100-preview.6.24325.8", it failed to launch with error: ```System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information```.

**This is by design change and this is the [Official BinaryFormatter removal announcement](https://github.com/dotnet/runtime/issues/98245) for your reference. We are filing this issue and would like to give you a heads-up if you are going to upgrade to .NET 9.** 

Here is some comments/suggestion from team:
1. Everyone should stop using BinaryFormatter.
2. To the extent that (1) is not possible, the application can reference the System.Runtime.Serialization.Formatters nuget package (the 9.0 version line), and that will bring BinaryFormatter back to the functionality it had in .NET 8.

Please refer to https://github.com/dotnet/runtime/issues/103952 for more detailed information.

================
### Steps to Reproduce
1. Set EnableUnsafeBinaryFormatterSerialization switch to True and set 9.0.100-preview.6.24325.8 runtime version in NetTopologySuiteTest02\NetTopologySuite.Tests.NUnit.runtimeconfig.json
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.6.24321.8"
      }
    ],
"configProperties": {
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": true
    }

2. Cd to NetTopologySuite\NetTopologySuiteTest02
3. Run "dotnet vstest NetTopologySuite.Tests.NUnit.dll"
```

  Expected Result:
  All pass.
  
  Actual Result:
  Error Message:
```
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerializable [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerializable [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerializable [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerializable [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerializable [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerializable [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerializable [< 1 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Geometries.Implementation.CoordinateSequenceTestBase.TestSerializable() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Geometries\Implementation\CoordinateSequenceTestBase.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed TestSerialization [427 ms]
  Error Message:
   System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
  Stack Trace:
     at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NetTopologySuite.Tests.NUnit.Utilities.SerializationUtility.Serialize[T](T obj) in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Utilities\SerializationUtility.cs:line 15
   at NetTopologySuite.Tests.NUnit.Index.Quadtree.QuadtreeTest.TestSerialization() in C:\source\NetTopologySuite\test\NetTopologySuite.Tests.NUnit\Index\Quadtree\QuadtreeTest.cs:line 43
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
Application Name: NetTopologySuite(UnitTest)
OS： Windows 10 21H2
CPU: X64
.NET Build Number: dotnet-sdk-9.0.100-preview.7.24321.3
Github Link: https://github.com/NetTopologySuite/NetTopologySuite

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by bjornharrtell** [comment]
I believe this is a non-issue. Serialization is only used for testing and is explicitly using the unsupported nuget dependency for this, as documented for use cases where the risk is acceptable which I strongly believe is the case here.
