### ISSUE TITLE
GeoJsonReader cannot read array of int arrays property

### ISSUE THREAD

**Issue by jnicho02** [NetTopologySuite/NetTopologySuite#92]
Hi,

My team wish to deserialize/serialize arrays of arrays in geojson properties. From my tests it would appear that an array of json-object-arrays is okay, but an array of primitive-arrays isn't.

Regards,
              Jez

WhenArrayOfIntArraysPropertyInGeoJsonThenReadable fails with:
System.ArgumentException: Expected a property name.
Result StackTrace:	
at NetTopologySuite.IO.Converters.FeatureCollectionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
```
{
    [TestClass]
    public class NetTopologySuiteCanSerializeAndDeserializeGeoJson
    {
        private Feature _feature;
        private GeoJsonReader _reader;
        private GeoJsonWriter _writer;

        [TestInitialize]
        public void GivenAGeoJsonReaderAndWriter()
        {
            _reader = new GeoJsonReader();
            _writer = new GeoJsonWriter();
            var geometry = new Point(1, 2);
            _feature = new Feature(geometry, new AttributesTable());
        }

        [TestMethod]
        public void WhenArrayOfJsonObjectArraysPropertyInGeoJsonThenReadable()
        {
            const string geojsonString = @"
{
  ""type"":""FeatureCollection"",
  ""features"":[
    {
      ""type"":""Feature"",
      ""geometry"":{
        ""type"":""Point"",
        ""coordinates"":[1.0,2.0]
      },
      ""properties"":{
        ""foo"":[
          {
            ""xyz"":[
                {""zee"":""xyz""},
                {""hay"":""zus""}
            ]
          }
        ]
      }
    }
  ]
}
";
            var featureCollection = _reader.Read<FeatureCollection>(geojsonString);
            Assert.AreEqual(1, featureCollection.Count);
        }

        [TestMethod]
        public void WhenArrayOfJsonObjectArraysPropertyInGeoJsonThenWriteable()
        {
            const string geojsonString = @"
{
  ""type"":""FeatureCollection"",
  ""features"":[
    {
      ""type"":""Feature"",
      ""geometry"":{
        ""type"":""Point"",
        ""coordinates"":[1.0,2.0]
      },
      ""properties"":{
        ""foo"":[
          {
            ""xyz"":[
                {""zee"":""xyz""},
                {""hay"":""zus""}
            ]
          }
        ]
      }
    }
  ]
}
";
            var featureCollection = _reader.Read<FeatureCollection>(geojsonString);
            var written = _writer.Write(featureCollection);
            Assert.IsTrue(written.Contains("FeatureCollection"));
        }

        [TestMethod]
        public void WhenArrayOfIntArraysPropertyInFeatureThenWritable()
        {
            var arrayOfInts = new[] {1, 2, 3};
            var anotherArrayOfInts = new[] {4, 5, 6};
            var arrayOfArrays = new[] {arrayOfInts, anotherArrayOfInts};
            _feature.Attributes.AddAttribute("foo", arrayOfArrays);
            var written = _writer.Write(_feature);
            Assert.IsTrue(written.Contains("Feature"));
        }

        [TestMethod]
        public void WhenArrayOfIntArraysPropertyInGeoJsonThenReadable()
        {
            const string geojsonString = @"
{
    ""type"":""Feature"",
    ""geometry"":{
        ""type"":""Point"",""coordinates"":[1.0,2.0]},
        ""properties"":{
            ""foo"":[[1,2,3],[4,5,6]]
        }
    }
}
";
            var featureCollection = _reader.Read<FeatureCollection>(geojsonString);
            Assert.AreEqual(1, featureCollection.Count);
        }
    }
}
```

**Comment by jnicho02** [comment]
Sorry, update on that, it doesn't really like arrays of primitives, let alone arrays-of-arrays.
```
        [TestMethod]
        public void WhenPopulatedIntArrayPropertyInGeoJsonThenReadable()
        {
            const string geojsonString = @"
{
  ""type"": ""FeatureCollection"",
  ""features"": [
    {
      ""type"": ""Feature"",
      ""geometry"": {
        ""type"": ""Point"",
        ""coordinates"": [1.0,2.0]
      },
      ""properties"": {
        ""foo"": [1, 2]
      }
    }
  ]
}
";
            var featureCollection = _reader.Read<FeatureCollection>(geojsonString);
            Assert.AreEqual(1, featureCollection.Count);
        }
```
gives me a System.ArgumentException: Expected token '{' not found.
Result StackTrace:	
at NetTopologySuite.IO.Converters.AttributesTableConverter.InternalReadJson(JsonReader reader, JsonSerializer serializer)

**Comment by FObermaier** [comment]
I have committed a fix for this and #93. Could you please verify that it works for you, too?
Btw, the json in `WhenArrayOfIntArraysPropertyInGeoJsonThenReadable` is not correct. It is not a `FeatureCollection` and there is a closing curly bracket too many.

**Comment by jnicho02** [comment]
dang, sorry about the test. I must have done a last minute edit and messed it up.

Is it in a branch? (I can probably find it myself...)

**Comment by jnicho02** [comment]
Okay. I see them in https://github.com/NetTopologySuite/NetTopologySuite/commit/4e286fba0b7c4b8383a73fc739ab843a1d394a3f

**Comment by jnicho02** [comment]
Well, I can see my tests in GitHubIssues.cs and they all pass, so happy days :) Thank you for fixing so quickly.

The big question is when do you have a NuGet package release planned? I quite understand that you can't go releasing every time the tiniest change is made. It would be painful to build from source and host it on nuget server because we don't want to be out-of-synch with the major versioning.

**Comment by FObermaier** [comment]
I might be able to update just the GeoJSON package. If so, I'll see if I can do that over the weekend
